name: Yahoo Fantasy Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '45 11 * * *'        # 7:45 AM US/Eastern
    - cron: '0 12-22 * * 1-5'    # Hourly 8AM–6PM ET, Mon–Fri

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Run fetcher
        env:
          YAHOO_CLIENT_ID: ${{ secrets.YAHOO_CLIENT_ID }}
          YAHOO_CLIENT_SECRET: ${{ secrets.YAHOO_CLIENT_SECRET }}
          YAHOO_REFRESH_TOKEN: ${{ secrets.YAHOO_REFRESH_TOKEN }}
        run: |
          python scripts/fetch_yahoo.py

      - name: Upload data artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yahoo-data
          path: data
          if-no-files-found: ignore

      - name: Commit data (if changed) and push
        run: |
          echo ">>> listing repo root"; ls -la
          echo ">>> listing data/"; ls -la data || true
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A data
          git status
          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "Update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
