name: Yahoo Fantasy Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "45 11 * * *"
    - cron: "0 12-22 * * 1-5"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Run fetcher
        env:
          YAHOO_CLIENT_ID: ${{ secrets.YAHOO_CLIENT_ID }}
          YAHOO_CLIENT_SECRET: ${{ secrets.YAHOO_CLIENT_SECRET }}
          YAHOO_REFRESH_TOKEN: ${{ secrets.YAHOO_REFRESH_TOKEN }}
        run: |
          python scripts/fetch_yahoo.py

      - name: Upload data artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yahoo-data
          path: data

      - name: Commit data (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "Update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Push
        if: success()
        run: |
          git push
